# <div align='center'> Stack,VStack,HStack </div>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
a.shape, a, b

((3,), array([1, 2, 3]), array([4, 5, 6]))

In [4]:
aa = np.array([[1], [2], [3]])
bb = np.array([[4], [5], [6]])

In [5]:
aa.shape, aa, bb

((3, 1), array([[1],
        [2],
        [3]]), array([[4],
        [5],
        [6]]))

## numpy.stack

In [6]:
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.stack((aa, bb), axis=0)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [9]:
t = np.stack((aa, bb), axis=1)
t.shape, t

((3, 2, 1), array([[[1],
         [4]],
 
        [[2],
         [5]],
 
        [[3],
         [6]]]))

## numpy.vstack

In [10]:
# 行拼接
np.vstack((a, b)) # = np.stack(axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.vstack((aa, bb))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## numpy.hstack

In [12]:
# 列拼接
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [13]:
np.hstack((aa, bb))

array([[1, 4],
       [2, 5],
       [3, 6]])

## numpy.concatenate

In [14]:
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.concatenate((aa, bb), axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
np.concatenate((aa, bb), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## 一维列拼接

In [17]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])